parser: "@typescript-eslint/parser"
parserOptions:
  ecmaVersion: 6
  project: "./tsconfig.json"
env:
  browser: false
  node: true
  es6: true
extends:
- eslint:recommended
- plugin:@typescript-eslint/recommended
- plugin:@typescript-eslint/recommended-requiring-type-checking
- plugin:@typescript-eslint/eslint-recommended
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
plugins:
- "@typescript-eslint"
rules:
  "@typescript-eslint/no-explicit-any": 'off'
  "@typescript-eslint/camelcase": 'off'
  "@typescript-eslint/naming-convention":
  - error
  - selector: variableLike
    format:
    - camelCase
    leadingUnderscore: allow
  - selector: variable
    format:
    - camelCase
    - UPPER_CASE
  "@typescript-eslint/no-unused-vars":
  - warn
  - argsIgnorePattern: "^_"