service: hathor-wallet-service
frameworkVersion: '2'

useDotenv: true

custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true
  prune:
    automatic: true
    number: 3
  authorizer:
    walletBearer:
      name: bearerAuthorizer
      type: TOKEN
      identitySource: method.request.header.Authorization
      identityValidationExpression: Bearer (.*)
  # Configures throttling settings for the API Gateway stage
  # They apply to all http endpoints, unless specifically overridden
  apiGatewayThrottling:
    maxRequestsPerSecond: 500
    maxConcurrentRequests: 250

plugins:
  - serverless-offline
  - serverless-webpack
  - serverless-prune-plugin
  - serverless-api-gateway-throttling

resources:
  Resources:
    WalletServiceNewTxQueue:
      Type: "AWS::SQS::Queue"
      Properties:
        QueueName:
            WalletServiceNewTxQueue_${opt:stage, 'dev'}

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  # In MB. This is the memory allocated for the Lambdas, they cannot use more than this
  # and will break if they try.
  memorySize: 256
  # This is the default timeout. Each function can specify a different value
  timeout: 6
  websocketsApiName: wallet-realtime-ws-api-${opt:stage, 'dev'}
  websocketsApiRouteSelectionExpression: $request.body.action
  vpc:
    securityGroupIds:
      - ${env:AWS_VPC_DEFAULT_SG_ID}
    subnetIds:
      - ${env:AWS_SUBNET_ID_1}
      - ${env:AWS_SUBNET_ID_2}
      - ${env:AWS_SUBNET_ID_3}
  apiGateway:
    minimumCompressionSize: 1024 # Enable gzip compression for responses > 1 KB
  environment:
    ADMINTOKEN: ${env:ADMINTOKEN}
    AUTH_SECRET: ${env:AUTH_SECRET}
    AWS_VPC_DEFAULT_SG_ID: ${env:AWS_VPC_DEFAULT_SG_ID}
    AWS_SUBNET_ID_1: ${env:AWS_SUBNET_ID_1}
    AWS_SUBNET_ID_2: ${env:AWS_SUBNET_ID_2}
    AWS_SUBNET_ID_3: ${env:AWS_SUBNET_ID_3}
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1
    BLOCK_REWARD_LOCK: ${env:BLOCK_REWARD_LOCK}
    CONFIRM_FIRST_ADDRESS: ${env:CONFIRM_FIRST_ADDRESS}
    DB_ENDPOINT: ${env:DB_ENDPOINT}
    DB_PORT: ${env:DB_PORT}
    DB_NAME: ${env:DB_NAME}
    DB_USER: ${env:DB_USER}
    DB_PASS: ${env:DB_PASS}
    MAX_ADDRESS_GAP: ${env:MAX_ADDRESS_GAP}
    NETWORK: ${env:NETWORK}
    NEW_TX_SQS: { Ref: WalletServiceNewTxQueue }
    REDIS_HOST: ${env:REDIS_HOST}
    REDIS_PORT: ${env:REDIS_PORT}
    REDIS_PASSWORD: ${env:REDIS_PASSWORD}
    SERVICE_NAME: ${self:service}
    STAGE: ${opt:stage, 'dev'}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - sqs:*
      Resource:
        Fn::GetAtt: [ WalletServiceNewTxQueue, Arn ]

functions:
  getLatestBlock:
    handler: src/height.getLatestBlock
  onNewTxRequest:
    handler: src/txProcessor.onNewTxRequest
  onHandleReorgRequest:
    handler: src/txProcessor.onHandleReorgRequest
    timeout: 300 # 5 minutes
  onSearchForLatestValidBlockRequest:
    handler: src/txProcessor.onSearchForLatestValidBlockRequest
  onNewTxEvent:
    handler: src/txProcessor.onNewTxEvent
  loadWalletAsync:
    handler: src/api/wallet.loadWallet
  loadWalletApi:
    role: arn:aws:iam::769498303037:role/WalletServiceLoadWalletLambda
    handler: src/api/wallet.load
    events:
      - http:
          path: wallet/init
          method: post
          cors: true
  getWalletStatusApi:
    handler: src/api/wallet.get
    events:
      - http:
          path: wallet/status
          method: get
          cors: true
          authorizer: ${self:custom.authorizer.walletBearer}
  getAddressesApi:
    handler: src/api/addresses.get
    events:
      - http:
          path: wallet/addresses
          method: get
          cors: true
          authorizer: ${self:custom.authorizer.walletBearer}
  getNewAddresses:
    handler: src/api/newAddresses.get
    events:
      - http:
          path: wallet/addresses/new
          method: get
          cors: true
          authorizer: ${self:custom.authorizer.walletBearer}
  getUtxos:
    handler: src/api/utxos.getFilteredUtxos
    events:
      - http:
          path: wallet/utxos
          method: get
          cors: true
          authorizer: ${self:custom.authorizer.walletBearer}
  getBalanceApi:
    handler: src/api/balances.get
    events:
      - http:
          path: wallet/balances
          method: get
          cors: true
          authorizer: ${self:custom.authorizer.walletBearer}
  getTokensApi:
    handler: src/api/tokens.get
    events:
      - http:
          path: wallet/tokens
          method: get
          cors: true
          authorizer: ${self:custom.authorizer.walletBearer}
  getTxHistoryApi:
    handler: src/api/txhistory.get
    events:
      - http:
          path: wallet/history
          method: get
          cors: true
          authorizer: ${self:custom.authorizer.walletBearer}
  createTxProposalApi:
    handler: src/api/txProposalCreate.create
    events:
      - http:
          path: tx/proposal
          method: post
          cors: true
          authorizer: ${self:custom.authorizer.walletBearer}
  sendTxProposalApi:
    handler: src/api/txProposalSend.send
    events:
      - http:
          path: tx/proposal/{txProposalId}
          method: put
          cors: true
          authorizer: ${self:custom.authorizer.walletBearer}
          request:
            parameters:
              paths:
                txProposalId: true
  deleteTxProposalApi:
    handler: src/api/txProposalDestroy.destroy
    events:
      - http:
          path: tx/proposal/{txProposalId}
          method: delete
          cors: true
          authorizer: ${self:custom.authorizer.walletBearer}
          request:
            parameters:
              paths:
                txProposalId: true
  wsConnect:
    handler: src/ws/connection.connect
    timeout: 1
    events:
      - websocket:
          route: $connect
      - websocket:
          route: $disconnect
      - websocket:
          route: ping
  wsJoin:
    handler: src/ws/join.handler
    timeout: 1
    events:
      - websocket:
          route: join
  wsTxNotifyNew:
    handler: src/ws/txNotify.onNewTx
    timeout: 1
    events:
      - sqs:
          arn:
            Fn::GetAtt:
              - WalletServiceNewTxQueue
              - Arn
          batchSize: 10
          maximumBatchingWindow: 60
  wsTxNotifyUpdate:
    handler: src/ws/txNotify.onUpdateTx
    timeout: 1
  wsAdminBroadcast:
    handler: src/ws/admin.broadcast
    timeout: 1
  wsAdminDisconnect:
    handler: src/ws/admin.disconnect
    timeout: 1
  wsAdminMulticast:
    handler: src/ws/admin.multicast
    timeout: 1
  authTokenApi:
    handler: src/api/auth.tokenHandler
    timeout: 6
    events:
      - http:
          path: auth/token
          method: post
          cors: true
  bearerAuthorizer:
    handler: src/api/auth.bearerAuthorizer
  metrics:
    handler: src/metrics.getMetrics
    events:
      - http:
          path: metrics
          method: get
          throttling:
            maxRequestsPerSecond: 2
            maxConcurrentRequests: 2
