service:
  name: hathor-wallet-service

custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true
  prune:
    automatic: true
    number: 3
  authorizer:
    walletBearer:
      name: bearerAuthorizer
      type: TOKEN
      identitySource: method.request.header.Authorization
      identityValidationExpression: Bearer (.*)

# Create an optimized package for our functions
# package:
#   individually: true

plugins:
  - serverless-offline
  - serverless-webpack
  - serverless-prune-plugin
  - serverless-dotenv-plugin

resources:
  Resources:
    WalletServiceNewTxQueue:
      Type: "AWS::SQS::Queue"
      Properties:
        QueueName:
            WalletServiceNewTxQueue_${opt:stage, 'dev'}

provider:
  name: aws
  runtime: nodejs12.x
  websocketsApiName: wallet-realtime-ws-api
  websocketsApiRouteSelectionExpression: $request.body.action
  vpc:
    securityGroupIds:
      - ${env:AWS_VPC_DEFAULT_SG_ID}
    subnetIds:
      - ${env:AWS_SUBNET_ID_1}
      - ${env:AWS_SUBNET_ID_2}
      - ${env:AWS_SUBNET_ID_3}
  apiGateway:
    minimumCompressionSize: 1024 # Enable gzip compression for responses > 1 KB
  environment:
    AWS_VPC_DEFAULT_SG_ID: ${env:AWS_VPC_DEFAULT_SG_ID}
    AWS_SUBNET_ID_1: ${env:AWS_SUBNET_ID_1}
    AWS_SUBNET_ID_2: ${env:AWS_SUBNET_ID_2}
    AWS_SUBNET_ID_3: ${env:AWS_SUBNET_ID_3}
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1
    SERVICE_NAME: ${self:service}
    NETWORK: ${env:NETWORK}
    MAX_ADDRESS_GAP: ${env:MAX_ADDRESS_GAP}
    BLOCK_REWARD_LOCK: ${env:BLOCK_REWARD_LOCK}
    ADMINTOKEN: ${env:ADMINTOKEN}
    CONFIRM_FIRST_ADDRESS: ${env:CONFIRM_FIRST_ADDRESS}
    DB_ENDPOINT: ${env:DB_ENDPOINT}
    DB_PORT: ${env:DB_PORT}
    DB_NAME: ${env:DB_NAME}
    DB_USER: ${env:DB_USER}
    DB_PASS: ${env:DB_PASS}
    NEW_TX_SQS: { Ref: WalletServiceNewTxQueue }
    REDIS_HOST: ${env:REDIS_HOST}
    REDIS_PORT: ${env:REDIS_PORT}
    REDIS_PASSWORD: ${env:REDIS_PASSWORD}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - sqs:*
      Resource:
        Fn::GetAtt: [ WalletServiceNewTxQueue, Arn ]

functions:
  getLatestBlock:
    handler: src/height.getLatestBlock
    timeout: 600
  onNewTxRequest:
    handler: src/txProcessor.onNewTxRequest
  onHandleReorgRequest:
    handler: src/txProcessor.onHandleReorgRequest
    timeout: 300 # 5 minutes
  onSearchForLatestValidBlockRequest:
    handler: src/txProcessor.onSearchForLatestValidBlockRequest
  onNewTxEvent:
    handler: src/txProcessor.onNewTxEvent
  loadWalletAsync:
    handler: src/api/wallet.loadWallet
  loadWalletApi:
    handler: src/api/wallet.load
    events:
      - http:
          path: wallet
          method: post
          cors: true
  getWalletStatusApi:
    handler: src/api/wallet.get
    events:
      - http:
          path: wallet
          method: get
          cors: true
          authorizer: ${self:custom.authorizer.walletBearer}
  getAddressesApi:
    handler: src/api/addresses.get
    events:
      - http:
          path: addresses
          method: get
          cors: true
          authorizer: ${self:custom.authorizer.walletBearer}
  getBalanceApi:
    handler: src/api/balances.get
    events:
      - http:
          path: balances
          method: get
          cors: true
          authorizer: ${self:custom.authorizer.walletBearer}
  getTxHistoryApi:
    handler: src/api/txhistory.get
    events:
      - http:
          path: txhistory
          method: get
          cors: true
          authorizer: ${self:custom.authorizer.walletBearer}
  createTxProposalApi:
    handler: src/api/txProposalCreate.create
    events:
      - http:
          path: txproposals
          method: post
          cors: true
          authorizer: ${self:custom.authorizer.walletBearer}
  sendTxProposalApi:
    handler: src/api/txProposalSend.send
    events:
      - http:
          path: txproposals/{txProposalId}
          method: put
          cors: true
          authorizer: ${self:custom.authorizer.walletBearer}
          request:
            parameters:
              paths:
                txProposalId: true
  deleteTxProposalApi:
    handler: src/api/txProposalDestroy.destroy
    events:
      - http:
          path: txproposals/{txProposalId}
          method: delete
          cors: true
          authorizer: ${self:custom.authorizer.walletBearer}
          request:
            parameters:
              paths:
                txProposalId: true
  wsConnect:
    handler: src/ws/connection.connect
    events:
      - websocket:
          route: $connect
      - websocket:
          route: $disconnect
      - websocket:
          route: ping
  wsJoin:
    handler: src/ws/join.handler
    events:
      - websocket:
          route: join
  wsTxNotifyNew:
    handler: src/ws/txNotify.onNewTx
    events:
      - sqs:
          arn:
            Fn::GetAtt:
              - WalletServiceNewTxQueue
              - Arn
          batchSize: 10
          maximumBatchingWindow: 60
  wsTxNotifyUpdate:
    handler: src/ws/txNotify.onUpdateTx
  wsAdminBroadcast:
    handler: src/ws/admin.broadcast
  wsAdminDisconnect:
    handler: src/ws/admin.disconnect
  wsAdminMulticast:
    handler: src/ws/admin.multicast
  authTokenApi:
    handler: src/api/auth.tokenHandler
    events:
      - http:
          path: auth/token
          method: post
          cors: true
  bearerAuthorizer:
    handler: src/api/auth.bearerAuthorizer
